FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ./GenerateAStrongPassword/GenerateAStrongPassword/GenerateAStrongPassword.csproj GenerateAStrongPassword.csproj
RUN dotnet restore GenerateAStrongPassword.csproj
COPY ./GenerateAStrongPassword/GenerateAStrongPassword/ .
WORKDIR /src
RUN dotnet build GenerateAStrongPassword.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish GenerateAStrongPassword.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "GenerateAStrongPassword.dll"]