resource "yandex_compute_disk" "boot-disk-1" {
  name     = "boot-disk-1"
  type     = "network-hdd"
  zone     = var.zone
  size     = var.disk_size
  image_id = var.image_id1
}

resource "yandex_compute_disk" "boot-disk-2" {
  name     = "boot-disk-2"
  type     = "network-hdd"
  zone     = var.zone
  size     = var.disk_size
  image_id = var.image_id1
}

resource "yandex_compute_instance" "vm-pub" {
  name = "terraform1"
  platform_id = "standard-v3"
  
  resources {
    cores  = var.cores
    memory = var.memory
  }

  boot_disk {
    disk_id = yandex_compute_disk.boot-disk-1.id
  }

  network_interface {
    subnet_id = "${yandex_vpc_subnet.subnet-pub.id}"
    nat       = var.nat
  }

  metadata = {
    user-data = "${file("metadata.yaml")}"
  }
}

resource "yandex_compute_instance" "vm-priv" {
  name = "terraform2"
  platform_id = "standard-v3"
  
  resources {
    cores  = var.cores
    memory = var.memory
  }

  boot_disk {
    disk_id = yandex_compute_disk.boot-disk-2.id
  }

  network_interface {
    subnet_id = "${yandex_vpc_subnet.subnet-priv.id}"
    nat       = var.nat
  }

  metadata = {
    user-data = "${file("metadata.yaml")}"
  }

#  provisioner "local-exec" {
#    command = <<-EOT
#      exec "sudo apt update"
#      exec "sudo apt install -y nginx"
#	  exec "sudo ufw allow 22/tcp"
#	  exec "sudo ufw allow 8080/tcp"
#    EOT
#	on_failure = continue
#  }
}

# generated by cmd: terraform plan -generate-config-out="generated.tf"
# __generated__ by Terraform from "fv4vvoolh41fs41ii61c"
resource "yandex_compute_instance" "default" {
  allow_recreate            = null
  allow_stopping_for_update = null
  description               = null
  folder_id                 = "b1g6ifc75l92cc8ek01e"
  gpu_cluster_id            = null
  hostname                  = "compute-vm-2-2-10-ssd-1741759650058"
  labels                    = {}
  maintenance_grace_period  = null
  maintenance_policy        = null
  metadata = {
    install-unified-agent = "0"
    serial-port-enable    = "0"
    ssh-keys              = "cdbuser:ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJjld2DacGIb6aQKKC/pge7VAtnfMqvItxaxAuSgxDev Технопарк@LNVTP"
    user-data             = "#cloud-config\ndatasource:\n Ec2:\n  strict_id: false\nssh_pwauth: no\nusers:\n- name: cdbuser\n  sudo: ALL=(ALL) NOPASSWD:ALL\n  shell: /bin/bash\n  ssh_authorized_keys:\n  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJjld2DacGIb6aQKKC/pge7VAtnfMqvItxaxAuSgxDev Технопарк@LNVTP"
  }
  name                      = "compute-vm-2-2-10-ssd-1741759650058"
  network_acceleration_type = "standard"
  platform_id               = "standard-v3"
  service_account_id        = null
  zone                      = "ru-central1-d"
  boot_disk {
    auto_delete = true
    device_name = "fv46foiet2vmelaj5dlq"
    disk_id     = "fv46foiet2vmelaj5dlq"
    mode        = "READ_WRITE"
    initialize_params {
      block_size  = 4096
      description = null
      image_id    = "fd8h7qn285s4tlkqqb2o"
      kms_key_id  = null
      name        = "disk-ubuntu-16-04-lts-1741759660179"
      size        = 10
      snapshot_id = null
      type        = "network-ssd"
    }
  }
  metadata_options {
    aws_v1_http_endpoint = 1
    aws_v1_http_token    = 2
    gce_http_endpoint    = 1
    gce_http_token       = 1
  }
  network_interface {
    index              = 0
    ip_address         = "10.131.0.24"
    ipv4               = true
    ipv6               = false
    ipv6_address       = null
    nat                = true
    nat_ip_address     = null
    security_group_ids = []
    subnet_id          = "fl8l5fnsrn66a27ogqkk"
  }
  network_interface {
    index              = 1
    ip_address         = null
    ipv4               = true
    ipv6               = false
    ipv6_address       = null
    nat                = true
    nat_ip_address     = null
    security_group_ids = ["enpnbg44oe1cv4ul4me4"]
    subnet_id          = "fl89cnq7ohab1ugti3o8"
  }
  placement_policy {
    host_affinity_rules       = []
    placement_group_id        = null
    placement_group_partition = 0
  }
  resources {
    core_fraction = 100
    cores         = 2
    gpus          = 0
    memory        = 2
  }
  scheduling_policy {
    preemptible = false
  }
  
}

#test
output "external_ip_address_vm_3" {
  value = yandex_compute_instance.default.network_interface.1.ip_address
}