{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-np
  namespace: {{ .Values.networkPolicies.namespace | quote }}
spec:
  policyTypes:
  {{- if .Values.networkPolicies.ingress }}
  - Ingress
  {{- end }}
  podSelector:
    matchLabels:
      app: {{ .Values.networkPolicies.selectorForApp }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.networkPolicies.selectorFromApp }}
{{- end }}