apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.name" . }}-svc
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}-service
spec:
  type: {{ .Values.StatesfulCfgWP.svcType }}
  ports:
    - port: {{ .Values.StatesfulCfgWP.svcPort }}
  selector:
    {{- include "mysql.AppName" . | nindent 4 }}