pipeline { 
    agent any 
	environment {
        ProjDir1 = 'Hello Devops'
		ProjDir2 = 'Hello Jenkins'
        ProjDir3 = 'Hello World'
    }
    stages { 
        stage("Compile & Build Binary") { 
			parallel {
				stage('stage project-a') {
					stages {
						stage('Build') {
							steps {
								dir("${env.ProjDir1}") { 
									sh 'mvn -B -DskipTests clean package'
								}
							}
						}
						stage('Test') {
							steps {
								sh 'mvn test'
							}
							post {
								always {
									junit 'target/surefire-reports/*.xml'
								}
							}
						}
						stage('Deliver') { 
							steps {
								sh './jenkins/scripts/deliver.sh' 
							}
						}
					}
				}
				stage('stage project-b') {
					stages {
						stage('Build') {
							steps {
								dir("${env.ProjDir2}") { 
									sh 'mvn -B -DskipTests clean package'
								}
							}
						}
						stage('Test') {
							steps {
								sh 'mvn test'
							}
							post {
								always {
									junit 'target/surefire-reports/*.xml'
								}
							}
						}
						stage('Deliver') { 
							steps {
								sh './jenkins/scripts/deliver.sh' 
							}
						}
					}
				}
				stage('stage project-c') {
					stages {
						stage('Build') {
							steps {
								dir("${env.ProjDir1}") { 
									sh 'mvn -B -DskipTests clean package'
								}
							}
						}
						stage('Test') {
							steps {
								sh 'mvn test'
							}
							post {
								always {
									junit 'target/surefire-reports/*.xml'
								}
							}
						}
						stage('Deliver') { 
							steps {
								sh './jenkins/scripts/deliver.sh' 
							}
						}
					}
				}
            } 
        } 
    } 
}