---

- name: Install the correct MySQL for RHEL
  ansible.builtin.import_tasks: mysql_centos.yml
  when: ansible_facts['os_family']|lower == 'redhat'
  
- name: Install the correct MySQL for Debian
  ansible.builtin.import_tasks: mysql_ubuntu.yml
  when: ansible_facts['os_family']|lower == 'debian'
