apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-wpcfm
data:
  WORDPRESS_DB_HOST: {{ .Values.secretParams.dbHost }}
  WORDPRESS_DB_USER: {{ .Values.secretParams.dbUser }}
  WORDPRESS_DB_NAME: {{ .Values.secretParams.dbName }}
  APACHE_RUN_DIR: {{ .Values.secretParams.runDir }}


