apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "wordpress.name" . }}-store
provisioner: {{ .Values.StorageClass.provisioner }} 
volumeBindingMode: {{ .Values.StorageClass.volumeBindingMode }}
