apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wordpress.name" . }}-sa
  namespace: {{ .Values.serviceAccount.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.serviceAccount.namespace }}
  name: pods-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pods-reader-bnd
  namespace: {{ .Values.serviceAccount.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pods-reader
subjects:
- kind: ServiceAccount
  name: {{ include "wordpress.name" . }}-sa
  namespace: {{ .Values.serviceAccount.namespace }}
---
apiVersion: v1
kind: Pod
metadata:
  name: diag-pod
  namespace: {{ .Values.serviceAccount.namespace }}
spec:
  containers:
  - image: bibinwilson/docker-kubectl:latest
    name: kubectl
  serviceAccountName: {{ include "wordpress.name" . }}-sa